### ISSUE TITLE
Add `"jsnext": "src/index.js",` to `package.json`

### ISSUE THREAD

**Issue by ansballard** [bspaulding/preact-custom-element#5]
I'm currently working on a little preact boilerplate for standalone components, and thought this might be a nice addition to it. But I'm bundling with rollup, and it would be nice to be able to pull in the es6 module version of this library without an alias or workaround. Shouldn't be any code changes since the source is already es6. just needs the `jsnext` field added to `package.json`.

**Comment by bspaulding** [comment]
I'm cool with it. PR's welcome!

**Comment by ansballard** [comment]
Awesome, I'll see if I can't get to it tonight/this weekend.
